language: node_js
node_js:
  - "lts/*"
env:
  - TEST_DIR=ravello-auth
  - TEST_DIR=ravello-blueprints
cache:
  directories:
    - node_modules
before_script:
  - cd $TEST_DIR
  - npm install
script: 
  - npm test
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage